### PR TITLE
Drone to CircleCI

### PR DESCRIPTION
**Pull request by peggyl**

### CODE REVIEW

**Comment by peggyl** [comment]
`Permission denied (password,publickey).` from the local SFTP test server

**Comment by peggyl** [comment]
Note: self-assigned so it shows up in the list of things I'm tracking / check in on, but will work with @jefff and @nathanleiby to get this done.

**Comment by nathanleiby** [comment]
It looks like just the `-race` test (1 to 2 tests) are failing now. And they're failing intermittently 😆 

These are rebuilds of the same commit:

- https://circleci.com/gh/Clever/sftp/24 (1 test failed)
- https://circleci.com/gh/Clever/sftp/26 (2 tests failed)

The kind of errors we're seeing are:
```
conn err:  accept tcp 127.0.0.1:38396: use of closed network connection
ssh server socket closed: accept tcp 127.0.0.1:38396: use of closed network connection
```

**Comment by nathanleiby** [comment]
I tried to fork it and run on travis CI to see if our version was more stable there, but hit vendoring issues. https://travis-ci.org/nathanleiby/sftp/jobs/198123738 Probably _not_ going to dig into this more today.. though would be awesome if we could solve it since this is the last repo that needs to be migrated from Drone -> Circle!

**Comment by nathanleiby** [comment]
I'm able to reproduce the kinds of errors I hit in 8b2bde6 locally. To reproduce them, I ran [`make test-circle` (minus the SSH keygen command)](https://github.com/Clever/sftp/blob/c93b259205045bfa60d28d32a892c3477d354a7b/Makefile#L17-L22)

This suggests that the `-race` tests may legitimately have issues, independent from running on CircleCI

**Comment by nathanleiby** [comment]
@peggyl @jefff @mohit 

I've been able to re-produce the same kind of race errors running in a Docker container locally, too.

I also notice that this commit was added to the upstream to fix failing `-race` tests https://github.com/pkg/sftp/issues/153 ... I tried applying it but unfortunately it didn't seem to fix the tests for me. Certainly seems worth pulling in all upstream changes though!

---

As far as this PR, I suggest that we merge the repo in the condition it was in from Drone (see alternate PR: https://github.com/Clever/sftp/pull/17) and work on fixing the failing `-race` tests separately. It doesn't seem caused by CircleCI.

**Pull request closed without merging**
